apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      run: hello-world
  template:
    metadata:
      labels:
        run: hello-world
    spec:
      containers:
      - name: hello-world
        image: us.icr.io/sn-labs-ctriboi/hello-world:1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 50m
            memory: 30Mi
          requests:
            cpu: 20m
            memory: 10Mi  
        
      imagePullSecrets:
        - name: icr
